### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wmy23333** [MinChen00/Graph-Unlearning#5]
Where does this file come from？
FileNotFoundError: [Errno 2] No such file or directory: 'temp_data/models/citeseer/GAT_random_1_0.005_0.9_0_0_1'

**Comment by MinChen00** [comment]
Hi, I’m not sure how you encountered this error. The temp_data directory primarily stores the pre-trained model, preprocessed data, or intermediate results. I suggest checking the error stack to identify the root cause. If you need further assistance, feel free to provide more details, and I’ll be happy to help.

**Comment by wmy23333** [comment]
Thank you, I have solved this problem, but I have encountered a new problem.When I loaded the CS dataset, I encountered the following error.And loading cs and Physics both encountered this problem.
![3a39c06299674a54a81d50e2f9cd79a3](https://github.com/user-attachments/assets/7256e792-47b2-4a3e-9226-4d2fbcb097aa)

**Comment by Surosy** [comment]
> Where does this file come from？这个文件从哪里来？ FileNotFoundError: [Errno 2] No such file or directory: 'temp_data/models/citeseer/GAT_random_1_0.005_0.9_0_0_1'FileNotFoundError：[Errno 2]没有这样的文件或目录：'temp_data/models/citeseer/GAT_random_1_0.005_0.9_0_0_1'

Hello, How is this problem solved, I am also experiencing the same problem
